version: '3.9'
services:
  kafka-3:
    image: egais/kafka:3.0.0_kraft
    hostname: kafka-3
    container_name: kafka-3
    networks:
      - cmp
    environment:
      - TZ=Europe/Minsk
      - KAFKA_BROKER_ID=3
      - KAFKA_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:19095
      - NUM_PARTITIONS=2    
# Example for adding quorum        
#      - KAFKA_QUORUM_VOTERS=1@kafka-1:19093,2@kafka-2:19094,3@lcoalhost:19095
      - KAFKA_HEAP_OPTS=-Xmx1024m -Xms1024m
      - RANDOM_UUID=w3CdhAhgREK86CbkscJ7dg
    volumes:
      - "./kraft-combined-logs:/tmp/kraft-combined-logs"
      - "./kafka_logs:/opt/kafka/logs"
networks:
  cmp:
    name: cmp
    driver: bridge
    ipam:
      driver: default
      config: 
        - subnet: "172.50.5.0/24"
